"""empty message

Revision ID: 072b361575a2
Revises: ef9ea3b86927
Create Date: 2023-03-15 16:10:44.226550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072b361575a2'
down_revision = 'ef9ea3b86927'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('birth', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('preferences', sa.String(length=300), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('school', sa.String(length=100), nullable=True),
    sa.Column('others', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('birth', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('childs',
    sa.Column('tutor_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['tutor_id'], ['tutor.id'], ),
    sa.PrimaryKeyConstraint('tutor_id', 'child_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_tutor', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_advertiser', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_advertiser')
        batch_op.drop_column('is_tutor')

    op.drop_table('childs')
    op.drop_table('tutor')
    op.drop_table('child')
    # ### end Alembic commands ###
