"""empty message

Revision ID: e2fa737f8b50
Revises: b584bd120b44
Create Date: 2023-03-22 20:30:00.664541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2fa737f8b50'
down_revision = 'b584bd120b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventhistory',
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertiser.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('advertiser_id', 'event_id')
    )
    with op.batch_alter_table('advertiser', schema=None) as batch_op:
        batch_op.drop_constraint('advertiser_events_fkey', type_='foreignkey')
        batch_op.drop_column('events')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('advertiser', schema=None) as batch_op:
        batch_op.add_column(sa.Column('events', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('advertiser_events_fkey', 'event', ['events'], ['id'])

    op.drop_table('eventhistory')
    # ### end Alembic commands ###
